# Generated by Django 4.2.16 on 2024-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_logo'),
        ),
    ]
