# Generated by Django 4.2.16 on 2024-12-04 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinchat',
            unique_together={('user', 'chat')},
        ),
    ]
